sudo: required
services:
    - docker

before_install:
    - docker build -t bradw73/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run bradw73/react-test npm run test -- --coverage

after_success:
    # This list of all containers needed for this application
    - docker build -t bradw73/multi-client ./client
    - docker build -t bradw73/multi-nginx ./nginx
    - docker build -t bradw73/multi-server ./server
    - docker build -t bradw73/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take these images and push them to hub.docker.com
    - docker push bradw73/multi-client
    - docker push bradw73/multi-nginx
    - docker push bradw73/multi-server
    - docker push bradw73/multi-worker

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-164643404721"
    bucket_path: "docker-multi"
    on:
        branch_name: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"


